### ISSUE TITLE
Cannot find handshakes

### ISSUE THREAD

**Issue by ghost** [derv82/capjs#1]
I've modified Main.js to attempt to crack a handshake after using the filechooser and in the browser console log, I get the error:

    Uncaught Error: No handshakes found(...)      CapFile.js:811

These are the modifications I have made so far:

    // FileChooser
    document.querySelector('#fileChooser').addEventListener('change', function() {
        var reader = new FileReader();
        reader.onload = function(){
            var capfile = new CapFile(this.result, debug);
            loadCapfile(capfile);
            
            handshake = capfile.extractPmkFields();
            var crack = new Crack(handshake);
            alert(crack.tryPSK("Test123"));
        }
        reader.readAsBinaryString(this.files[0]);
    }, false);

and here is the PCAP file I'm using: https://dl.dropbox.com/s/xan3tr8fmwy4buc/LBT_00-72-82-A0-F2-E4.cap

**Comment by derv82** [comment]
There's only 3 handshakes in that cap file:

![capjs_3handshakes](https://user-images.githubusercontent.com/993464/37251305-86f97af2-24c2-11e8-8144-b0ab59f8411a.PNG)

capjs requires all 4 handshakes.

I don't know how to crack the PSK using only the first 3 handshakes...
